# Generated by Django 5.0.1 on 2024-02-01 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_moviecollection_event_collection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Project',
        ),
    ]
