# Generated by Django 5.0.1 on 2024-02-01 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='auth_User',
        ),
    ]
