# Generated by Django 5.0.1 on 2024-02-09 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_profile_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='virtual_event_link',
            field=models.URLField(blank=True, max_length=500, null=True, validators=[django.core.validators.URLValidator()]),
        ),
    ]
